-- ============================================================================
--  LIMPIEZA EL BARRIO — Esquema de base de datos (PostgreSQL)
-- ============================================================================
--  Orden de ejecución: 1) schema.sql  2) data.sql
--  Ejemplo:
--    psql "$DATABASE_URL" -f schema.sql
--    psql "$DATABASE_URL" -f data.sql
--
--  Notas de diseño:
--   * Las imágenes NO se guardan como BLOB: sólo se almacena una URL externa
--     (S3, Cloudinary, Google Drive, etc.) en la columna productos.imagen_url.
--   * Una misma foto sirve para todas las variantes (tamaño/aroma) del producto,
--     evitando duplicar imágenes.
--   * Dinero en NUMERIC(12,2) -> BigDecimal en Java.
--   * Enumeraciones como VARCHAR + CHECK para mantener el esquema portable y
--     simple de mapear con @Enumerated(EnumType.STRING) en JPA.
-- ============================================================================

BEGIN;

-- Limpieza (útil para re-ejecutar el script durante el desarrollo)
DROP TABLE IF EXISTS pedido_items CASCADE;
DROP TABLE IF EXISTS pedidos     CASCADE;
DROP TABLE IF EXISTS variantes   CASCADE;
DROP TABLE IF EXISTS productos   CASCADE;
DROP TABLE IF EXISTS categorias  CASCADE;

-- ----------------------------------------------------------------------------
-- CATEGORÍAS
-- ----------------------------------------------------------------------------
CREATE TABLE categorias (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     VARCHAR(80)  NOT NULL,
    slug       VARCHAR(80)  NOT NULL UNIQUE,
    icono      VARCHAR(16),
    orden      INT          NOT NULL DEFAULT 0,
    activa     BOOLEAN      NOT NULL DEFAULT TRUE,
    destacada  BOOLEAN      NOT NULL DEFAULT FALSE
);

-- ----------------------------------------------------------------------------
-- PRODUCTOS
-- ----------------------------------------------------------------------------
CREATE TABLE productos (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_id BIGINT       NOT NULL REFERENCES categorias (id),
    nombre       VARCHAR(120) NOT NULL,
    slug         VARCHAR(140) NOT NULL UNIQUE,
    descripcion  TEXT,
    imagen_url   TEXT         NOT NULL,              -- URL externa, nunca BLOB
    destacado    BOOLEAN      NOT NULL DEFAULT FALSE, -- banner "Combos y Ofertas"
    activo       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- ----------------------------------------------------------------------------
-- VARIANTES (presentaciones / aromas / tamaños de un mismo producto)
-- ----------------------------------------------------------------------------
CREATE TABLE variantes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id   BIGINT        NOT NULL REFERENCES productos (id) ON DELETE CASCADE,
    presentacion  VARCHAR(120)  NOT NULL,            -- ej: "750 ml", "Aroma Limón"
    precio        NUMERIC(12,2) NOT NULL CHECK (precio >= 0),
    precio_oferta NUMERIC(12,2)          CHECK (precio_oferta IS NULL OR precio_oferta >= 0),
    stock         INT           NOT NULL DEFAULT 0,
    activa        BOOLEAN       NOT NULL DEFAULT TRUE,
    orden         INT           NOT NULL DEFAULT 0
);

-- ----------------------------------------------------------------------------
-- PEDIDOS (copia del pedido que el cliente envía por WhatsApp)
-- ----------------------------------------------------------------------------
CREATE TABLE pedidos (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_cliente   VARCHAR(120) NOT NULL,
    telefono         VARCHAR(30),
    direccion        VARCHAR(255),
    barrio           VARCHAR(120),
    modalidad_entrega VARCHAR(30) NOT NULL
        CHECK (modalidad_entrega IN ('RETIRO_LOCAL', 'ENVIO_DOMICILIO')),
    medio_pago       VARCHAR(30) NOT NULL
        CHECK (medio_pago IN ('EFECTIVO', 'TRANSFERENCIA', 'MERCADO_PAGO')),
    notas            TEXT,
    total            NUMERIC(12,2) NOT NULL DEFAULT 0,
    estado           VARCHAR(30) NOT NULL DEFAULT 'NUEVO'
        CHECK (estado IN ('NUEVO', 'CONFIRMADO', 'ENTREGADO', 'CANCELADO')),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ----------------------------------------------------------------------------
-- ITEMS DE PEDIDO (snapshot: guarda nombre/precio al momento de la compra)
-- ----------------------------------------------------------------------------
CREATE TABLE pedido_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id       BIGINT        NOT NULL REFERENCES pedidos (id) ON DELETE CASCADE,
    producto_id     BIGINT,
    variante_id     BIGINT,
    producto_nombre VARCHAR(160)  NOT NULL,
    variante_nombre VARCHAR(160),
    cantidad        INT           NOT NULL CHECK (cantidad > 0),
    precio_unitario NUMERIC(12,2) NOT NULL,
    subtotal        NUMERIC(12,2) NOT NULL
);

-- ----------------------------------------------------------------------------
-- ÍNDICES
-- ----------------------------------------------------------------------------
CREATE INDEX idx_productos_categoria  ON productos (categoria_id);
CREATE INDEX idx_productos_nombre     ON productos (nombre);
CREATE INDEX idx_productos_destacado  ON productos (destacado) WHERE destacado; -- parcial
CREATE INDEX idx_variantes_producto   ON variantes (producto_id);
CREATE INDEX idx_pedido_items_pedido  ON pedido_items (pedido_id);
CREATE INDEX idx_pedidos_created      ON pedidos (created_at DESC);

COMMIT;
