-- ============================================================================
--  AROMA A LIMPIO — Esquema idempotente (classpath)
--  Se ejecuta AUTOMÁTICAMENTE al arrancar la app (spring.sql.init.mode=always).
--  Todo usa "IF NOT EXISTS", así que se puede correr las veces que haga falta
--  sin borrar datos ni fallar.
-- ============================================================================

CREATE TABLE IF NOT EXISTS categorias (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     VARCHAR(80)  NOT NULL,
    slug       VARCHAR(80)  NOT NULL UNIQUE,
    icono      VARCHAR(16),
    orden      INT          NOT NULL DEFAULT 0,
    activa     BOOLEAN      NOT NULL DEFAULT TRUE,
    destacada  BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS productos (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_id  BIGINT       NOT NULL REFERENCES categorias (id),
    nombre        VARCHAR(120) NOT NULL,
    slug          VARCHAR(140) NOT NULL UNIQUE,
    descripcion   TEXT,
    imagen_url    TEXT         NOT NULL,
    codigo_barras VARCHAR(64),
    destacado     BOOLEAN      NOT NULL DEFAULT FALSE,
    activo        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS variantes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id   BIGINT        NOT NULL REFERENCES productos (id) ON DELETE CASCADE,
    presentacion  VARCHAR(120)  NOT NULL,
    precio        NUMERIC(12,2) NOT NULL CHECK (precio >= 0),
    precio_oferta NUMERIC(12,2)          CHECK (precio_oferta IS NULL OR precio_oferta >= 0),
    stock         INT           NOT NULL DEFAULT 0,
    activa        BOOLEAN       NOT NULL DEFAULT TRUE,
    orden         INT           NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS pedidos (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_cliente   VARCHAR(120) NOT NULL,
    telefono         VARCHAR(30),
    direccion        VARCHAR(255),
    barrio           VARCHAR(120),
    modalidad_entrega VARCHAR(30) NOT NULL
        CHECK (modalidad_entrega IN ('RETIRO_LOCAL', 'ENVIO_DOMICILIO')),
    medio_pago       VARCHAR(30) NOT NULL
        CHECK (medio_pago IN ('EFECTIVO', 'TRANSFERENCIA', 'MERCADO_PAGO')),
    notas            TEXT,
    total            NUMERIC(12,2) NOT NULL DEFAULT 0,
    estado           VARCHAR(30) NOT NULL DEFAULT 'NUEVO'
        CHECK (estado IN ('NUEVO', 'CONFIRMADO', 'ENTREGADO', 'CANCELADO')),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pedido_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id       BIGINT        NOT NULL REFERENCES pedidos (id) ON DELETE CASCADE,
    producto_id     BIGINT,
    variante_id     BIGINT,
    producto_nombre VARCHAR(160)  NOT NULL,
    variante_nombre VARCHAR(160),
    cantidad        INT           NOT NULL CHECK (cantidad > 0),
    precio_unitario NUMERIC(12,2) NOT NULL,
    subtotal        NUMERIC(12,2) NOT NULL
);

-- ----------------------------------------------------------------------------
-- Índices (idempotentes)
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_productos_categoria ON productos (categoria_id);
CREATE INDEX IF NOT EXISTS idx_productos_nombre    ON productos (nombre);
CREATE INDEX IF NOT EXISTS idx_productos_destacado ON productos (destacado) WHERE destacado;
CREATE INDEX IF NOT EXISTS idx_variantes_producto  ON variantes (producto_id);
CREATE INDEX IF NOT EXISTS idx_pedido_items_pedido ON pedido_items (pedido_id);
CREATE INDEX IF NOT EXISTS idx_pedidos_created     ON pedidos (created_at DESC);

-- Índice único del código de barras (alta/actualización con lector)
CREATE UNIQUE INDEX IF NOT EXISTS uq_productos_codigo_barras
    ON productos (codigo_barras)
    WHERE codigo_barras IS NOT NULL;

-- Índice único para que el alta masiva de variantes sea idempotente
CREATE UNIQUE INDEX IF NOT EXISTS uq_variantes_producto_presentacion
    ON variantes (producto_id, presentacion);
